export const GET_CARDS_SUCCESSFUL = 'GET_CARDS_SUCCESSFUL'
export const GET_CARDS_FAILED = 'GET_CARDS_FAILED'
export const UPDATE_CARD_SUCCESSFUL = 'UPDATE_CARD_SUCCESSFUL'
export const UPDATE_CARD_FAILED = 'UPDATE_CARD_FAILED'