export const GET_CARDS_SUCCESSFUL = 'GET_CARDS_SUCCESSFUL'
export const GET_CARDS_FAILED = 'GET_CARDS_FAILED'
export const MAKE_CARD_DEFAULT_SUCCESSFUL = 'MAKE_CARD_DEFAULT_SUCCESSFUL'
export const MAKE_CARD_DEFAULT_FAILED = 'MAKE_CARD_DEFAULT_FAILED'